### PR TITLE
docs(README): add Arch Linux installation instructions

### PR DESCRIPTION
**Pull request by adamperkowski**
hey. packaged kri for arch :)

### CODE REVIEW

**Comment by ikozyris** [comment]
I planned to package it for the 0.8.1 (see the [release schedule](https://github.com/users/ikozyris/projects/6/views/9)), due to the name change which was the next commit after the 0.8 release.
Does it install everything as the .deb? Or Arch doesn't require the same files to be installed as Debian?
The license isn't `GPL-3.0-only`, it is `GPL-3+`.
With what build flags did you build it? Don't build with `march=native`, it will cause problems for CPUs with different hardware (e.g. not supporting AVX-2). I built for `x86-64-v2` (~2008).

**Comment by adamperkowski** [comment]
i saw the name change, took care of that - the installed binary is `kri`

___

i assumed `GPL-3.0-only` because you left the template `(at your option)` in the readme:
https://github.com/ikozyris/kri/blob/28db5459fd2265c7cf928bbfdfd4a30489ae8191/README.md?plain=1#L49-L50
a nice idea would be to remove it

___

if `-march=native` causes problems, why is it in the Makefile?

i'm sorry but as an outside person i have no idea about that stuff...

**Comment by ikozyris** [comment]
The license is `GPL-3-or-later` which is the same thing as `GPL-3+`. Which means it can be relicensed for `GPL-4-or-later` when (or if) the license gets updated, but not `GPL-4-only`.

The `march=native` flag is used in the Makefile to optimize for the specific computer used. Compile with `march=x86-64-v2`, or don't put `march` at all.

**Comment by adamperkowski** [comment]
> The license is `GPL-3-or-later` which is the same thing as `GPL-3+`. Which means it can be relicensed for `GPL-4-or-later` when (or if) the license gets updated, but not `GPL-4-only`.

i understand that. again, i assumed `GPL-3.0-only` because the license notice in the README doesn't specify the version. it says `(at your option)`, which is a template notice included in the license.

> The `march=native` flag is used in the Makefile to optimize for the specific computer used. Compile with `march=x86-64-v2`, or don't put `march` at all.

1. the AUR is different from official Arch repositories. in official repositories, the package is being built once on Arch servers and the "`pkg`" "artifacts" are being distributed, packages in the AUR are meant to be built during installation.
2. the official Arch distribution is x86_64 only. the package, on the other hand, is locked to `x86_64` so if it were to be built first and then distributed, other architectures wouldn't be able to install it anyway

**Comment by ikozyris** [comment]
@adamperkowski can you make me the maintainer of the package in AUR, same username as here.

**Comment by adamperkowski** [comment]
sure

**Pull request merged**
